"""add Department

Revision ID: 8165e75c9f8c
Revises: ff7bdddc79cd
Create Date: 2024-10-02 16:23:11.045887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8165e75c9f8c'
down_revision = 'ff7bdddc79cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
